Repository opentk/opentk, pull requests merged in 2022-01, with the labels that each got.

#1348 Fix IL generation for some edge case GLES functions.
  src/Generator.Rewrite/Program.cs
Labels: binding generator, 4.x

#1359 Changed Span<T> to ReadOnlySpan<T> in OpenAL bindings where appropriate.
  src/OpenAL/OpenTK.OpenAL/AL/AL.cs
Labels: 4.x, OpenAL

#1344 Updated to GLFW 3.3.5
  src/OpenTK.Windowing.GraphicsLibraryFramework/OpenTK.Windowing.GraphicsLibraryFramework.csproj
Labels: 4.x

#1366 Marked NativeWindowSettings.IsFullscreen as obsolete.
  src/OpenTK.Windowing.Desktop/NativeWindowSettings.cs
Labels: 4.x

#1349 Added video mode information to MonitorInfo
  src/OpenTK.Windowing.Desktop/MonitorInfo.cs
  src/OpenTK.Windowing.Desktop/Monitors.cs
  src/OpenTK.Windowing.GraphicsLibraryFramework/GLFW.cs
  src/OpenTK.Windowing.GraphicsLibraryFramework/GLFWNative.cs
Labels: 4.x, glfw

#1350 Wrapped all GLFW callback functions in exception handlers
  .config/dotnet-tools.json
  LocalTest/LocalTest.csproj
  LocalTest/Program.cs
  OpenTK.sln
  build.fsx
  build.fsx.lock
  src/OpenTK.Windowing.Desktop/NativeWindow.cs
Labels: 4.x, glfw

#1369 Fix OnUnload
  src/OpenTK.Windowing.Desktop/GameWindow.cs
Labels: 4.x

#1334 Create no Context, when Context API = none
  src/OpenTK.Windowing.Desktop/GameWindow.cs
  src/OpenTK.Windowing.Desktop/NativeWindow.cs
Labels: 4.x

#1371 Fixed MapRange Methods
  src/OpenTK.Mathematics/MathHelper.cs
Labels: bug, 4.x, math
