Repository opentk/opentk, pull requests merged in 2023-10, with the labels that each got.

#1653 Add missing enums from KHR_Debug to GetPName
  src/Generator.Bind/Specifications/GL2/overrides.xml
Labels: 4.x, OpenGL

#1650 Fixed issue with Fullscreen -> Normal
  src/OpenTK.Windowing.Desktop/NativeWindow.cs
Labels: platform, 4.x, glfw

#1661 Added a small example into IBingingsContext interface.
  src/OpenTK.Core/Context/IBindingsContext.cs
Labels: documentation, 4.x, OpenGL

#1626 Support enum group namespaces in generator
  src/Generator/GeneratorSettings.cs
  src/Generator/Parsing/DocumentationParser.cs
  src/Generator/Parsing/SpecificationData.cs
  src/Generator/Parsing/SpecificationParser.cs
  src/Generator/Process/OutputData.cs
  src/Generator/Process/Overloaders.cs
  src/Generator/Process/Processor.cs
  src/Generator/Program.cs
  src/Generator/SpecificationFiles/gl.xml
  src/Generator/SpecificationFiles/wgl.xml
  src/Generator/Utility/ArrayUtil.cs
  src/Generator/Utility/NameMangler.cs
  src/Generator/Writer.cs
  src/OpenTK.Graphics/GL.Pointers.cs
  src/OpenTK.Graphics/GLX.Pointers.cs
  src/OpenTK.Graphics/Glx/Enums.cs
  src/OpenTK.Graphics/Glx/GLX.Native.cs
  src/OpenTK.Graphics/Glx/GLX.Overloads.cs
  src/OpenTK.Graphics/OpenGL/Compatibility/Enums.cs
  src/OpenTK.Graphics/OpenGL/Compatibility/GL.Manual.cs
  src/OpenTK.Graphics/OpenGL/Compatibility/GL.Native.cs
  src/OpenTK.Graphics/OpenGL/Compatibility/GL.Overloads.cs
  src/OpenTK.Graphics/OpenGL/Enums.cs
  src/OpenTK.Graphics/OpenGL/GL.Manual.cs
  src/OpenTK.Graphics/OpenGL/GL.Native.cs
  src/OpenTK.Graphics/OpenGL/GL.Overloads.cs
  src/OpenTK.Graphics/OpenGLES1/Enums.cs
  src/OpenTK.Graphics/OpenGLES1/GL.Native.cs
  src/OpenTK.Graphics/OpenGLES1/GL.Overloads.cs
  src/OpenTK.Graphics/OpenGLES2/Enums.cs
  src/OpenTK.Graphics/OpenGLES2/GL.Manual.cs
  src/OpenTK.Graphics/OpenGLES2/GL.Native.cs
  src/OpenTK.Graphics/OpenGLES2/GL.Overloads.cs
  src/OpenTK.Graphics/WGL.Pointers.cs
  src/OpenTK.Graphics/Wgl/Enums.cs
  src/OpenTK.Graphics/Wgl/WGL.Native.cs
  src/OpenTK.Graphics/Wgl/WGL.Overloads.cs
Labels: binding generator, 5.x, OpenGL

#1664 [5.0] Pre 5.0.0-pre9 changes
  src/Generator/Parsing/DocumentationData.cs
  src/Generator/Parsing/SpecificationData.cs
  src/Generator/Parsing/SpecificationParser.cs
  src/Generator/Process/OutputData.cs
  src/Generator/Process/Overloaders.cs
  src/Generator/Process/Processor.cs
  src/Generator/Program.cs
  src/Generator/Reader.cs
  src/Generator/SpecificationFiles/wgl.xml
  src/Generator/Utility/Extensions/IndentedTextWriterExtensions.cs
  src/Generator/Utility/Extensions/XElementExtensions.cs
  src/Generator/Utility/Logger.cs
  src/Generator/Utility/NameMangler.cs
  src/Generator/Writer.cs
  src/OpenTK.Graphics/GL.Pointers.cs
  src/OpenTK.Graphics/GLX.Pointers.cs
  src/OpenTK.Graphics/Glx/Enums.cs
  src/OpenTK.Graphics/Glx/GLX.Native.cs
  src/OpenTK.Graphics/Glx/GLX.Overloads.cs
  src/OpenTK.Graphics/OpenGL/Compatibility/Enums.cs
  src/OpenTK.Graphics/OpenGL/Compatibility/GL.Native.cs
  src/OpenTK.Graphics/OpenGL/Compatibility/GL.Overloads.cs
  src/OpenTK.Graphics/OpenGL/Enums.cs
  src/OpenTK.Graphics/OpenGL/GL.Native.cs
  src/OpenTK.Graphics/OpenGL/GL.Overloads.cs
  src/OpenTK.Graphics/OpenGLES1/Enums.cs
  src/OpenTK.Graphics/OpenGLES1/GL.Native.cs
  src/OpenTK.Graphics/OpenGLES1/GL.Overloads.cs
  src/OpenTK.Graphics/OpenGLES2/Enums.cs
  src/OpenTK.Graphics/OpenGLES2/GL.Native.cs
  src/OpenTK.Graphics/OpenGLES2/GL.Overloads.cs
  src/OpenTK.Graphics/Types.cs
  src/OpenTK.Graphics/WGL.Pointers.cs
  src/OpenTK.Graphics/Wgl/Enums.cs
  src/OpenTK.Graphics/Wgl/WGL.Native.cs
  src/OpenTK.Graphics/Wgl/WGL.Overloads.cs
  tests/OpenTK.Backends.Tests/ImGuiController.cs
  tests/OpenTK.Backends.Tests/Program.cs
  tests/OpenTK.Benchmarks/MatrixBenchmark.cs
  tests/OpenTK.Benchmarks/OpenTK.Benchmarks.csproj
  tests/OpenTK.Benchmarks/Program.cs
Labels: binding generator, 5.x, OpenGL
