Repository opentk/opentk, pull requests merged in 2023-09, with the labels that each got.

#1639 Typo fixed
  src/OpenTK.Windowing.Desktop/GameWindow.cs
Labels: bug, 4.x

#1646 4.8.0 hotfixes
  License.txt
  src/OpenAL/OpenTK.Audio.OpenAL/OpenALLibraryNameContainer.cs
  src/OpenTK.Compute/OpenCL/Enums.cs
  src/OpenTK.Compute/OpenCL/OpenCLLibraryNameContainer.cs
  src/OpenTK.Windowing.Desktop/GLFWProvider.cs
  src/OpenTK.Windowing.Desktop/GameWindow.cs
  src/OpenTK.Windowing.Desktop/NativeWindow.cs
  src/OpenTK.Windowing.GraphicsLibraryFramework/GLFW.cs
Labels: input, 4.x

#1625 Fix GLFWNative.LoadLibrary for Linux(X11, Wayland) with dotnet pusblish
  src/OpenTK.Windowing.GraphicsLibraryFramework/GLFWNative.cs
  src/OpenTK.Windowing.GraphicsLibraryFramework/OpenTK.Windowing.GraphicsLibraryFramework.csproj
  src/OpenTK.Windowing.GraphicsLibraryFramework/paket
Labels: platform, 4.x, glfw, linux, wayland
