Repository opentk/opentk, pull requests merged in 2023-02, with the labels that each got.

#1563 Update NativeWindow.cs
  src/OpenTK.Windowing.Desktop/NativeWindow.cs
Labels: documentation, 4.x

#1564 Update GLFW.cs
  src/OpenTK.Windowing.GraphicsLibraryFramework/GLFW.cs
Labels: documentation, 4.x

#1567 Fix monitor work area being reported incorrectly.
  src/OpenTK.Windowing.Desktop/MonitorInfo.cs
Labels: bug, 4.x, math

#1516 IFormattable implementations for vectors
  src/OpenTK.Mathematics/Data/Color4.cs
  src/OpenTK.Mathematics/Data/Half.cs
  src/OpenTK.Mathematics/Data/Quaternion.cs
  src/OpenTK.Mathematics/Data/Quaterniond.cs
  src/OpenTK.Mathematics/Geometry/Box2.cs
  src/OpenTK.Mathematics/Geometry/Box2d.cs
  src/OpenTK.Mathematics/Geometry/Box2i.cs
  src/OpenTK.Mathematics/Geometry/Box3.cs
  src/OpenTK.Mathematics/Geometry/Box3d.cs
  src/OpenTK.Mathematics/Geometry/Box3i.cs
  src/OpenTK.Mathematics/MathHelper.cs
  src/OpenTK.Mathematics/Matrix/Matrix2.cs
  src/OpenTK.Mathematics/Matrix/Matrix2d.cs
  src/OpenTK.Mathematics/Matrix/Matrix2x3.cs
  src/OpenTK.Mathematics/Matrix/Matrix2x3d.cs
  src/OpenTK.Mathematics/Matrix/Matrix2x4.cs
  src/OpenTK.Mathematics/Matrix/Matrix2x4d.cs
  src/OpenTK.Mathematics/Matrix/Matrix3.cs
  src/OpenTK.Mathematics/Matrix/Matrix3d.cs
  src/OpenTK.Mathematics/Matrix/Matrix3x2.cs
  src/OpenTK.Mathematics/Matrix/Matrix3x2d.cs
  src/OpenTK.Mathematics/Matrix/Matrix3x4.cs
  src/OpenTK.Mathematics/Matrix/Matrix3x4d.cs
  src/OpenTK.Mathematics/Matrix/Matrix4.cs
  src/OpenTK.Mathematics/Matrix/Matrix4d.cs
  src/OpenTK.Mathematics/Matrix/Matrix4x2.cs
  src/OpenTK.Mathematics/Matrix/Matrix4x2d.cs
  src/OpenTK.Mathematics/Matrix/Matrix4x3.cs
  src/OpenTK.Mathematics/Matrix/Matrix4x3d.cs
  src/OpenTK.Mathematics/Vector/Vector2.cs
  src/OpenTK.Mathematics/Vector/Vector2d.cs
  src/OpenTK.Mathematics/Vector/Vector2h.cs
  src/OpenTK.Mathematics/Vector/Vector2i.cs
  src/OpenTK.Mathematics/Vector/Vector3.cs
  src/OpenTK.Mathematics/Vector/Vector3d.cs
  src/OpenTK.Mathematics/Vector/Vector3h.cs
  src/OpenTK.Mathematics/Vector/Vector3i.cs
  src/OpenTK.Mathematics/Vector/Vector4.cs
  src/OpenTK.Mathematics/Vector/Vector4d.cs
  src/OpenTK.Mathematics/Vector/Vector4h.cs
  src/OpenTK.Mathematics/Vector/Vector4i.cs
Labels: 4.x, math

#1570 Added System.Drawing casts and added Box2i overload to GL.Viewport
  src/OpenTK.Graphics/ES20/Helper.cs
  src/OpenTK.Graphics/ES30/Helper.cs
  src/OpenTK.Graphics/OpenGL2/Helper.cs
  src/OpenTK.Graphics/OpenGL4/Helper.cs
  src/OpenTK.Mathematics/Geometry/Box2.cs
  src/OpenTK.Mathematics/Geometry/Box2i.cs
  src/OpenTK.Mathematics/Vector/Vector2.cs
  src/OpenTK.Mathematics/Vector/Vector2i.cs
Labels: 4.x, math

#1571 Better update accuracy on windows
  src/OpenTK.Windowing.Desktop/GameWindow.cs
  tests/LocalTest/Program.cs
Labels: 4.x
