Repository opentk/opentk, pull requests merged in 2024-11, with the labels that each got.

#1762 [5.0] Egl bindings
  src/Generator/Parsing/SpecificationData.cs
  src/Generator/Parsing/SpecificationParser.cs
  src/Generator/Process/OutputData.cs
  src/Generator/Process/Processor.cs
  src/Generator/Program.cs
  src/Generator/Reader.cs
  src/Generator/SpecificationFiles/egl.xml
  src/Generator/SpecificationFiles/egl_angle_ext.xml
  src/Generator/Writer.cs
  src/OpenTK.Graphics/EGL.Pointers.cs
  src/OpenTK.Graphics/EGLLoader.cs
  src/OpenTK.Graphics/Egl/EGL.Native.cs
  src/OpenTK.Graphics/Egl/EGL.Overloads.cs
  src/OpenTK.Graphics/Egl/Egl.cs
  src/OpenTK.Graphics/Egl/Enums.cs
  src/OpenTK.Graphics/GL.Pointers.cs
  src/OpenTK.Graphics/GLX.Pointers.cs
  src/OpenTK.Graphics/Glx/Enums.cs
  src/OpenTK.Graphics/Glx/GLX.Native.cs
  src/OpenTK.Graphics/Glx/GLX.Overloads.cs
  src/OpenTK.Graphics/OpenGL/Compatibility/Enums.cs
  src/OpenTK.Graphics/OpenGL/Compatibility/GL.Native.cs
  src/OpenTK.Graphics/OpenGL/Compatibility/GL.Overloads.cs
  src/OpenTK.Graphics/OpenGL/Enums.cs
  src/OpenTK.Graphics/OpenGL/GL.Native.cs
  src/OpenTK.Graphics/OpenGL/GL.Overloads.cs
  src/OpenTK.Graphics/OpenGLES1/Enums.cs
  src/OpenTK.Graphics/OpenGLES1/GL.Native.cs
  src/OpenTK.Graphics/OpenGLES1/GL.Overloads.cs
  src/OpenTK.Graphics/OpenGLES2/Enums.cs
  src/OpenTK.Graphics/OpenGLES2/GL.Native.cs
  src/OpenTK.Graphics/OpenGLES2/GL.Overloads.cs
  src/OpenTK.Graphics/Types.cs
  src/OpenTK.Graphics/WGL.Pointers.cs
  src/OpenTK.Graphics/Wgl/Enums.cs
  src/OpenTK.Graphics/Wgl/WGL.Native.cs
  src/OpenTK.Graphics/Wgl/WGL.Overloads.cs
  src/OpenTK.Platform/Interfaces/IOpenGLComponent.cs
  src/OpenTK.Platform/Native/ANGLE/ANGLEOpenGLComponent.cs
  src/OpenTK.Platform/Native/ANGLE/Handles.cs
  tests/ANGLETestProject/Program.cs
  tests/OpenTK.Backends.Tests/Program.cs
Labels: bindings generator, 5.x, ANGLE

#1764 Throw explicit exception and fix dispose when glfw fails to create window.
  src/OpenTK.Windowing.Desktop/NativeWindow.cs
Labels: bug, 4.x

#1765 Add missing GLFW 3.4 features to NativeWindow
  src/OpenTK.Windowing.Common/Enums/CursorState.cs
  src/OpenTK.Windowing.Desktop/GLFWProvider.cs
  src/OpenTK.Windowing.Desktop/NativeWindow.cs
  src/OpenTK.Windowing.GraphicsLibraryFramework/Enums/CursorModeValue.cs
Labels: improvement, 4.x

#1767 Add proper projection matrix extraction methods.
  src/OpenTK.Mathematics/Matrix/Matrix4.cs
  src/OpenTK.Mathematics/Matrix/Matrix4d.cs
  tests/OpenTK.Tests/Generators.fs
  tests/OpenTK.Tests/Matrix4Tests.fs
Labels: improvement, 4.x, math

#1768 Small fix to OpenAL enum documentation.
  src/OpenAL/OpenTK.Audio.OpenAL/AL/ALEnums.cs
Labels: improvement, documentation, 4.x, OpenAL

#1769 Fix starting window hidden on macos
  src/OpenTK.Windowing.Desktop/NativeWindow.cs
Labels: bug, upstream bug, 4.x, glfw

#1770 Update fullscreen/monitor API to be more reasonable.
  src/OpenTK.Windowing.Desktop/NativeWindow.cs
  src/OpenTK.Windowing.Desktop/NativeWindowSettings.cs
Labels: improvement, 4.x

#1755 Sign Assemblies
  OpenTK.snk
  build/build.fs
  src/Generator.Bind/Generator.Bind.csproj
  src/Generator.Converter/Generator.Convert.csproj
  src/Generator.Rewrite/Generator.Rewrite.csproj
  src/OpenAL/OpenALGenerator/OpenALGenerator.csproj
  src/OpenAL/OpenTK.Audio.OpenAL/OpenTK.Audio.OpenAL.csproj
  src/OpenAL/OpenTK.Audio.OpenAL/README.md
  src/OpenAL/OpenTK.Audio.OpenAL/paket
  src/OpenAL/OpenTK.OpenAL.Extensions/OpenTK.OpenAL.Extensions.csproj
  src/OpenTK.Compute/OpenTK.Compute.csproj
  src/OpenTK.Compute/README.md
  src/OpenTK.Compute/paket
  src/OpenTK.Core/OpenTK.Core.csproj
  src/OpenTK.Core/README.md
  src/OpenTK.Core/paket
  src/OpenTK.Graphics/OpenTK.Graphics.csproj
  src/OpenTK.Graphics/README.md
  src/OpenTK.Graphics/paket
  src/OpenTK.Input/OpenTK.Input.csproj
  src/OpenTK.Input/README.md
  src/OpenTK.Input/paket
  src/OpenTK.Mathematics/OpenTK.Mathematics.csproj
  src/OpenTK.Mathematics/README.md
  src/OpenTK.Mathematics/paket
  src/OpenTK.Windowing.Common/OpenTK.Windowing.Common.csproj
  src/OpenTK.Windowing.Common/README.md
  src/OpenTK.Windowing.Common/paket
  src/OpenTK.Windowing.Desktop/OpenTK.Windowing.Desktop.csproj
  src/OpenTK.Windowing.Desktop/README.md
  src/OpenTK.Windowing.Desktop/paket
  src/OpenTK.Windowing.GraphicsLibraryFramework/Input/JoystickState.cs
  src/OpenTK.Windowing.GraphicsLibraryFramework/OpenTK.Windowing.GraphicsLibraryFramework.csproj
  src/OpenTK.Windowing.GraphicsLibraryFramework/README.md
  src/OpenTK.Windowing.GraphicsLibraryFramework/paket
  tests/OpenALTest/OpenALTest.csproj
  tests/OpenTK.Tests/OpenTK.Tests.fsproj
Labels: improvement, 4.x, buildsystem

#1772 Document that slerping between vectors of opposite direction is undefined.
  src/OpenTK.Mathematics/Vector/Vector3.cs
  src/OpenTK.Mathematics/Vector/Vector3d.cs
  src/OpenTK.Mathematics/Vector/Vector4.cs
  src/OpenTK.Mathematics/Vector/Vector4d.cs
Labels: documentation, 4.x, math
